# Generated by Django 5.0.6 on 2024-06-23 13:17

from django.db import migrations

def create_standard_categories(apps, schema_editor):
    Category = apps.get_model('your_app_name', 'Category')
    standard_categories = [
        ('image', 'Image'),
        ('document', 'Document'),
        ('video', 'Video'),
    ]

    for code, name in standard_categories:
        Category.objects.create(name=name, is_standard=True)

class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_standard_categories),
    ]
