text_array = {
    'en': {
        'dashboard': 'Home Page',
        'profile': 'Profile',
        'logout': 'Log Out',
        'create_account': 'Sign Up',
        'login': 'Login',
        'my_notes': 'My Notes',
        'my_contacts': 'My Contacts',
        'addressbook': 'Address Book',
        'my_groups': 'Contact Groups',
        'contact_list': 'My Contacts',
        'showing_search_results_for': 'Showing search results for',
        'no_contacts_found_for': 'No contacts found for',
        'create_new_contact_question': 'Would you like to',
        'create_new_contact': 'create a new contact',
        'showing_contacts_for_group': 'Showing contacts for group',
        'no_contacts_for_group': 'No contacts found for the group',
        'you_can': 'You can',
        'add_new_contact': 'add a new contact',
        'no_contacts_yet': 'No contacts have been added yet.',
        'to_start': 'to get started.',
        'all': 'All',
        'search': 'Search',
        'reset': 'Reset',
        'search_field': 'Find...',
        'add_contact': 'Add Contact',
        'go_to_groups': 'Go to Groups',
        'create_contact': 'Create Contact',
        'update_contact': 'Update Contact',
        'edit': 'Edit',
        'delete': 'Delete',
        'confirm_delete_contact': 'Are you sure you want to delete the contact?',
        'name': 'Name',
        'name_placeholder': 'John Doe',
        'phone': 'Phone Number',
        'phone_placeholder': '+1-800-555-9900',
        'address': 'Address',
        'address_placeholder': '20 West 34th St., New York, NY 10001, USA',
        'email': 'Email',
        'email_placeholder': 'example@gmail.com',
        'birthday': 'Birthday',
        'birthday_placeholder': '01/01/1900',
        'created_at': 'Created on',
        'updated_at': 'Updated on',
        'group': 'Group',
        'groups': 'Groups',
        'create_group': 'Create Group',
        'update_group': 'Update Group',
        'group_name': 'Group Name',
        'group_name_placeholder': 'Enter group name',
        'family_group': 'Family',
        'friends_group': 'Friends',
        'work_group': 'Work',
        'create_button': 'Create',
        'update_button': 'Update',
        'cancel_button': 'Cancel',
        'group_list': 'The list of all your contact groups:',
        'group_list_empty': 'No contact group has been added yet.',
        'confirm_delete_group': 'Are you sure you want to delete the group?',
        'back_to_contacts': 'Back to Contacts',
        'add_group': 'Add New Group',
        'duplicate_contact': 'A contact with this name already exists.',
        'duplicate_group': 'A group with this name already exists.',
        'first': 'First',
        'previous': 'Previous',
        'page': 'Page',
        'of': 'of',
        'next': 'Next',
        'last': 'Last',
        'January': 'January',
        'February': 'February',
        'March': 'March',
        'April': 'April',
        'May': 'May',
        'June': 'June',
        'July': 'July',
        'August': 'August',
        'September': 'September',
        'October': 'October',
        'November': 'November',
        'December': 'December',
        'contact_not_found': 'Error! Contact not found!',
        'back_to_list': 'Back to List',
        'birthday_in_future': 'Birthday cannot be in the future.',
        'birthday_too_old': 'Birthday must be within the last 200 years.',
        'invalid_phone': 'Invalid phone number format.',
        'invalid_email': 'Invalid email address format.',
        'upcoming_birthdays_title': 'Upcoming Birthdays',
        'back_to_contact_list': 'Back to Contact List',
        'enter_days': 'Number of Days',
        'days_placeholder': 'Enter days',
        'submit': 'Submit',
        'upcoming_birthdays_for_next': 'Upcoming birthdays for the next',
        'days': 'days',
        'years_old': 'years old',
        'no_upcoming_birthdays': 'No upcoming birthdays within the specified days.'
    },
    'uk': {
        'dashboard': 'Головна сторінка',
        'profile': 'Профіль',
        'logout': 'Вийти',
        'create_account': 'Реєстрація',
        'login': 'Вхід',
        'my_notes': 'Мої нотатки',
        'my_contacts': 'Мої контакти',
        'addressbook': 'Книга контактів',
        'my_groups': 'Групи контактів',
        'contact_list': 'Мої контакти',
        'showing_search_results_for': 'Результати пошуку для',
        'no_contacts_found_for': 'Контакти не знайдені для',
        'create_new_contact_question': 'Бажаєте',
        'create_new_contact': 'створити новий контакт',
        'showing_contacts_for_group': 'Контакти для групи',
        'no_contacts_for_group': 'Немає контактів для групи',
        'you_can': 'Ви можете',
        'add_new_contact': 'додати новий контакт',
        'no_contacts_yet': 'Поки що жодного контакту не було додано.',
        'to_start': 'щоб почати.',
        'all': 'Всі',
        'search': 'Пошук',
        'reset': 'Скинути',
        'search_field': 'Знайти...',
        'add_contact': 'Додати контакт',
        'go_to_groups': 'Перейти до груп',
        'create_contact': 'Створити контакт',
        'update_contact': 'Оновити контакт',
        'edit': 'Редагувати',
        'delete': 'Видалити',
        'confirm_delete_contact': 'Ви впевнені, що хочете видалити контакт?',
        'name': "Ім'я",
        'name_placeholder': 'Іван Іванович',
        'phone': 'Номер телефону',
        'phone_placeholder': '+380990009900',
        'address': 'Адреса',
        'address_placeholder': 'Майдан Незалежності 1, Київ, Україна',
        'email': 'Електронна пошта',
        'email_placeholder': 'example@gmail.com',
        'birthday': 'Дата народження',
        'birthday_placeholder': '01/01/1900',
        'created_at': 'Створено',
        'updated_at': 'Оновлено',
        'group': 'Група',
        'groups': 'Групи',
        'create_group': 'Створити групу',
        'update_group': 'Оновити групу',
        'group_name': 'Назва групи',
        'group_name_placeholder': 'Введіть назву групи',
        'family_group': 'Сім\'я',
        'friends_group': 'Друзі',
        'work_group': 'Робота',
        'create_button': 'Створити',
        'update_button': 'Оновити',
        'cancel_button': 'Скасувати',
        'group_list': 'Список усіх ваших груп контактів:',
        'group_list_empty': 'Поки що жодної групи не було створено.',
        'confirm_delete_group': 'Ви впевнені, що хочете видалити групу?',
        'back_to_contacts': 'Список контактів',
        'add_group': 'Додати нову групу',
        'duplicate_contact': 'Контакт з таким ім’ям вже існує.',
        'duplicate_group': 'Група з такою назвою вже існує.',
        'first': 'Перша',
        'previous': 'Попередня',
        'page': 'Сторінка',
        'of': 'з',
        'next': 'Наступна',
        'last': 'Остання',
        'January': 'січня',
        'February': 'лютого',
        'March': 'березня',
        'April': 'квітня',
        'May': 'травня',
        'June': 'червня',
        'July': 'липня',
        'August': 'серпня',
        'September': 'вересня',
        'October': 'жовтня',
        'November': 'листопада',
        'December': 'грудня',
        'contact_not_found': 'Помилка! Контакт не знайдено!',
        'back_to_list': 'Назад до списку',
        'birthday_in_future': 'Дата народження не може бути у майбутньому.',
        'birthday_too_old': 'Дата народження повинна бути не раніше останніх 200 років.',
        'invalid_phone': 'Неправильний формат номера телефону.',
        'invalid_email': 'Неправильний формат електронної пошти.',
        'upcoming_birthdays_title': 'Дні народження',
        'back_to_contact_list': 'До списку контактів',
        'enter_days': 'Кількість днів',
        'days_placeholder': 'Введіть кількість днів',
        'submit': 'Надіслати',
        'upcoming_birthdays_for_next': 'Дні народження за наступні',
        'days': 'днів',
        'years_old': 'років',
        'no_upcoming_birthdays': 'Немає днів народження у вказаний період.'
    }
}
