text_array = {
                'en':{
                        'contact_latest':'Here is the list of your recent contacts:',
                        'contact_latest_empty':'There are no recent contacts yet.',
                        'contact_list':'Here is the list of all your contacts:',
                        'contact_list_empty':'No contacts have been added yet.',
                        'tag_list':'Here is the list of all your tags:',
                        'tag_list_empty':'No tags have been added yet.',
                        'tagged_contacts':'All contacts, associated with a tag',
                        'contact':'Contact',
                        'tag':'Tag',
                        'tags':'Tags',
                        'add':'Add',
                        'add_cont':'Add a new contact',
                        'add_tag':'Add a new tag',
                        'edit':'Edit',
                        'delete':'Delete',
                        'tag_edit':'Edit Tag',
                        'tag_delete':'Delete Tag',
                    },
                'ua':{
                        'latest':'',
                        'latest_empty':'',
                        'list':'',
                        'list_empty':'',
                        'contact':'Контакт',
                        'tag':'',
                        'tags':'Tags',
                        'add':'Add',
                        'add_cont':'Add a new contact',
                        'add_tag':'Add a new tag',
                        'edit':'Edit',
                        'delete':'Delete',
                    }
            }