text_array = {
                'en':{
                        'contact_latest':'Here is the list of your recent contacts:',
                        'contact_latest_empty':'There are no recent contacts yet.',
                        'contact_list':'Here is the list of all your contacts:',
                        'contact_list_empty':'No contacts have been added yet.',
                        'tag_list':'Here is the list of all your tags:',
                        'tag_list_empty':'No tags have been added yet.',
                        'tagged_contacts':'All contacts, associated with a tag',
                        'contact_not_found':'Error! Contact not found!',
                        'contact_name':'Name:',
                        'contact_phone':'Phone number:',
                        'contact_mail':'Email:',
                        'contact_address':'Address:',
                        'contact_creation':'Created on:',
                        'contact':'Contact',
                        'group':'Group',
                        'groups':'Groups',
                        'add':'Add',
                        'add_cont':'Add a new contact',
                        'add_group':'Add a new group',
                        'edit':'Edit',
                        'delete':'Delete',
                        'contact_edit':'Edit Contact',
                        'contact_delete':'Delete Contact',
                        'tag_edit':'Edit Tag',
                        'tag_delete':'Delete Tag',
                        'family_group_en': 'Family',
                        'family_group_uk': 'Сім\'я',
                        'friends_group_en': 'Friends',
                        'friends_group_uk': 'Друзі',
                        'work_group_en': 'Work',
                        'work_group_uk': 'Робота',
                        'name': 'Name',
                        'phone': 'Phone',
                        'address': 'Address',
                        'email': 'Email',
                        'birthday': 'Birthday',
                        'name_placeholder': 'John Doe',
                        'phone_placeholder': '+380990009900',
                        'address_placeholder': '20 West 34th St., New York, NY 10001, USA',
                        'email_placeholder': 'example@gmail.com',
                        'birthday_placeholder': '01/01/1900',
                        'group_name': 'Group name',
                        'group_placeholder': 'Group'
                    },
                'uk':{
                        'contact_latest':'Ось список останніх контактів:',
                        'contact_latest_empty':'Останніх контактів поки що немає.',
                        'contact_list':'Ось список усіх контактів:',
                        'contact_list_empty':'Поки що жодного контакту не було додано.',
                        'tag_list':'Ось список усіх тегів:',
                        'tag_list_empty':'Поки що жодного тегу не було додано.',
                        'tagged_contacts':'Усі контакти, що асоціюються з тегом',
                        'contact_not_found':'Помилка! Контакт не знайдено!',
                        'contact_name':'Ім`я:',
                        'contact_phone':'Номер телефону:',
                        'contact_mail':'Пошта:',
                        'contact_address':'Адреса:',
                        'contact_creation':'Створений:',
                        'contact':'Контакт',
                        'group':'Група',
                        'groups':'Групи',
                        'add':'Додати',
                        'add_cont':'Додати новий контакт',
                        'add_group':'Створити нову групу',
                        'edit':'Редагувати',
                        'delete':'Видалити',
                        'contact_edit':'Редагувати Контакт',
                        'contact_delete':'Видалити Контакт',
                        'tag_edit':'Редагувати Тег',
                        'tag_delete':'Видалити Тег',
                        'family_group_en': 'Family',
                        'family_group_uk': 'Сім\'я',
                        'friends_group_en': 'Friends',
                        'friends_group_uk': 'Друзі',
                        'work_group_en': 'Work',
                        'work_group_uk': 'Робота',
                        'name': "Ім'я",
                        'phone': 'Телефон',
                        'address': 'Адреса',
                        'email': 'Електронна пошта',
                        'birthday': 'Дата народження',
                        'name_placeholder': 'Іван Іванович',
                        'phone_placeholder': '+380990009900',
                        'address_placeholder': 'Майдан Незалежності 1, Київ, Україна',
                        'email_placeholder': 'example@gmail.com',
                        'birthday_placeholder': '01/01/1900',
                        'group_name': 'Назва групи',
                        'group_placeholder': 'Група'
                    }
            }