# Generated by Django 5.0.6 on 2024-06-24 14:15

import users.storage_avatar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', storage=users.storage_avatar.LocalStorage(), upload_to='profile_images'),
        ),
    ]
