# Generated by Django 5.0.6 on 2024-06-27 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0002_remove_post_post_author_remove_post_post_creator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(default='-', max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='birth_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='-', max_length=15, verbose_name='Birth month'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='-', max_length=30, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Unnamed contact', max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='-', max_length=12, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cm_tag_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
