# Generated by Django 5.0.6 on 2024-06-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0003_alter_contact_address_alter_contact_birth_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birth_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='-', max_length=20, verbose_name='Birth month'),
        ),
    ]
