# Generated by Django 5.0.6 on 2024-06-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0005_remove_tag_creator_remove_contact_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Group Name (English)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Group Name (Ukrainian)'),
        ),
    ]
