# Generated by Django 5.0.6 on 2024-06-30 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0006_alter_group_name_en_alter_group_name_uk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='group',
            name='group_of_creator_en',
        ),
        migrations.RemoveConstraint(
            model_name='group',
            name='group_of_creator_uk',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name_uk',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='Default Name', max_length=100, verbose_name='Group Name'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('creator', 'name'), name='unique_group_for_user'),
        ),
    ]
